apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::158433753848:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1CPMIZCSCH3DZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::158433753848:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-19T23:44:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1508"
  uid: 353d7577-f8cd-4af4-a24d-adce02b1f2ed
